/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Funfund } from "./Funfund";
export * as factories from "./factories";
export { Funfund__factory } from "./factories/Funfund__factory";
